### ISSUE TITLE
Prepare some predefined search ids for sentinel 2 mosaic in Mexico

### ISSUE THREAD

**Issue by geohacker** [developmentseed/pearl-backend#35]
We should look at https://planetarycomputer.microsoft.com/explore?c=-104.9008%2C22.8615&z=4.40&v=2 and prepare a few different seasons of mosaics that we can use as a starter. This is related and required for #32. 

We'll support advanced filters but this is important for a start.

cc @developmentseed/pearl

**Comment by geohacker** [comment]
Time | Mosaic ID
------|-----------
2019 December - 2020 March  | 2849689f57f1b3b9c1f725abb75aa411
2019 December - 2021 March | dce67bf58e5c9dbcf9393776f13f9ebd
2021 December - 2022 March | da05434b9b6a177a6999078221e19481
2022 December - 2023 February | 9406dbfba1d5416dc521857008180079


Thank to @vincentsarago for helping me with this!
@vgeorge @ingalls @srmsoumya we'll use these for predefined ranges now. The tile URL should look like:

`https://planetarycomputer.microsoft.com/api/data/v1/mosaic/tiles/{mosaic_id}/{z}/{x}/{y}?assets=B04&assets=B03&assets=B02&color_formula=Gamma+RGB+3.2+Saturation+0.8+Sigmoidal+RGB+25+0.35&collection=sentinel-2-l2a`

**Comment by geohacker** [comment]
Added this script as a helper here https://github.com/developmentseed/pearl-backend/blob/project-ts/helpers/create_sentinel_mosaic.py

**Comment by Rub21** [comment]
We have same script to create the Mosaic, https://github.com/developmentseed/reforestamos_data/blob/main/reforestamos_data/mosaic.py

**Comment by Rub21** [comment]
> https://planetarycomputer.microsoft.com/api/data/v1/mosaic/tiles/{mosaic_id}/{z}/{x}/{y}?assets=B04&assets=B03&assets=B02&color_formula=Gamma+RGB+3.2+Saturation+0.8+Sigmoidal+RGB+25+0.35&collection=sentinel-2-l2a

FYI,  we use `color_formula=Gamma+RGB+3.2+Saturation+0.8+Sigmoidal+RGB+25+0.35` for mapping, it helps to recognize the areas, but for getting the tiles for training we are not using  `color_formula`.

**Comment by Rub21** [comment]
@geohacker For the mosaics that you generate it would be good to check manually the corridors areas,  because some areas  in the mosaic may not look good. e.g 👇 

![image](https://user-images.githubusercontent.com/1152236/217917590-c5f66f4d-1264-4d6a-af64-628216cb4602.png)

We found that area  in the mosaic that we generated for mapping.  `2021-01-12T10:25:31Z to 2022-03-30T23:59:59Z`.: `82ebdc445544365e45be4db6d22536ec`

So, We had to generate another mosaic id for Maya corridor:  `2021-01-12T10:25:31Z` `to` `2022-01-30T23:59:59Z`: `a7e8b219131471cd41f67af99017626e`

**Comment by geohacker** [comment]
This is done. Thank you all!
